joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10 

left_arm_joint:
   type: effort_controllers/JointPositionController
   joint: joint_01
   pid: {p: 3.0, i: 0.0, d: 0}
   #pid: {p: 50.0, i: 0.1, d: 0.0}
right_arm_joint:
   type: effort_controllers/JointPositionController
   joint: joint_02
   pid: {p: 3.0, i: 0.0, d: 0}
   #pid: {p: 50.0, i: 0.1, d: 0.0}
