<?xml version="1.0"?>
<robot name="differential_wheeled_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  

  <xacro:include filename="$(find shadow-bot)/urdf/wheel.urdf.xacro" /> 

  <material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="Red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>

  <property name="M_PI" value="3.1415926535897931" />
  <property name="M_PI_2" value="1.570796327" />
  <property name="DEG_TO_RAD" value="0.017453293" />

  <!-- body -->
  <property name="base_mass" value="2.5" /> 

  <!-- arm -->
  <property name="arm_mass" value="0.15" /> 

  <!-- wheels -->
  <property name="wheel_mass" value="0.2" /> 
  
  <property name="base_x_origin_to_wheel_origin" value="-0.110" />
  <property name="base_y_origin_to_wheel_origin" value="0.095" />
  <property name="base_z_origin_to_wheel_origin" value="-0.005" />

  <property name="arm_x_origin_to_wheel_origin" value="0.160" />
  <property name="arm_y_origin_to_wheel_origin" value="-0.045" />
  <property name="arm_z_origin_to_wheel_origin" value="0.0" />

  <!-- inertia -->
  <macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
              izz="${m*r*r/2}" /> 
  </macro>

  <macro name="box_inertia" params="m x y z">
    <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
              iyy="${m*(x*x+z*z)/12}" iyz = "0"
              izz="${m*(x*x+y*y)/12}" /> 
  </macro>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
    </plugin>
  </gazebo>

 <link name="base_footprint">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>

  <gazebo reference="base_footprint">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius - base_z_origin_to_wheel_origin}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

  <link name="base_link">
    <inertial>
      <mass value="${base_mass}" />
      <origin xyz="0 0 0" />
      <!--The 3x3 rotational inertia matrix. -->
        <box_inertia  m="${base_mass}" x="0.262" y="0.150" z="0.06" />

    </inertial>    
    <visual>
      <origin xyz="0.015 0 -0.03" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://shadow-bot/meshes/dae/chassis.dae"/>
      </geometry>
      <material name="White" />
    </visual>  
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0 " />
      <geometry>
          <box size="0.262 0.150 0.06" />
      </geometry>
    </collision>     
  </link>
  <gazebo reference="base_link">
    <material>Gazebo/White</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <link name="left_arm">
    <inertial>
      <mass value="${arm_mass}" />
      <origin xyz="0.085 0 0" rpy="0 0 0 " />
      <!--The 3x3 rotational inertia matrix. -->
        <box_inertia  m="${arm_mass}" x="0.170" y="0.015" z="0.025" />

    </inertial>    
    <visual>
      <origin xyz="-0.0775 -0.13115 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://shadow-bot/meshes/dae/leftArmWheel.dae"/>
      </geometry>
      <material name="Black" />
    </visual>  
    <collision>
      <origin xyz="0.085 0 0" rpy="0 0 0 " />
      <geometry>
          <box size="0.170 0.015 0.025" />
      </geometry>
    </collision>     
  </link>
  <gazebo reference="left_link">
    <material>Gazebo/Black</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>
  
  <joint name="left_arm_joint" type="revolute">
    <parent link="base_link"/>
    <child link="left_arm"/>
    <origin xyz="0.0930 0.09 -0.0135" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="1000.0" lower="${-5*M_PI/12}" upper="${5*M_PI/12}" velocity="1000.0"/>
  </joint>

  <transmission name="left_arm_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_arm_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_arm_joint_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>10</mechanicalReduction>
    </actuator>
  </transmission>


  <link name="right_arm">
    <inertial>
      <mass value="${arm_mass}" />
      <origin xyz="0.085 0 0" rpy="0 0 0 " />
      <!--The 3x3 rotational inertia matrix. -->
        <box_inertia  m="${arm_mass}" x="0.170" y="0.015" z="0.025" />

    </inertial>    
    <visual>
      <origin xyz="-0.0775 0.05115 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://shadow-bot/meshes/dae/rightArmWheel.dae"/>
      </geometry>
      <material name="Black" />
    </visual>  
    <collision>
      <origin xyz="0.085 0 0" rpy="0 0 0 " />
      <geometry>
          <box size="0.170 0.015 0.025" />
      </geometry>
    </collision>     
  </link>
  <gazebo reference="right_link">
    <material>Gazebo/Black</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>
  
  <joint name="right_arm_joint" type="revolute">
    <parent link="base_link"/>
    <child link="right_arm"/>
    <origin xyz="0.0930 -0.09 -0.0135" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="1000.0" lower="${-5*M_PI/12}" upper="${5*M_PI/12}" velocity="1000.0"/>
  </joint>

  <transmission name="right_arm_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_arm_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_arm_joint_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>10</mechanicalReduction>
    </actuator>
  </transmission>


<!-- Wheel Definitions -->

  <wheel fb="front" lr="right" parent="base_link" translateX="${base_x_origin_to_wheel_origin}" translateY="${base_y_origin_to_wheel_origin}" translateZ="${base_z_origin_to_wheel_origin}" flipY="1"/>
  <wheel fb="front" lr="left" parent="base_link" translateX="${base_x_origin_to_wheel_origin}" translateY="-${base_y_origin_to_wheel_origin}" translateZ="${base_z_origin_to_wheel_origin}" flipY="1"/>
	   
  <arm_wheel fb="arm" lr="right" parent="right_arm" translateX="${arm_x_origin_to_wheel_origin}" translateY="${arm_y_origin_to_wheel_origin}" translateZ="${arm_z_origin_to_wheel_origin}" flipY="1"/>
  <arm_wheel fb="arm" lr="left" parent="left_arm" translateX="${arm_x_origin_to_wheel_origin}" translateY="${-1 * arm_y_origin_to_wheel_origin}" translateZ="${arm_z_origin_to_wheel_origin}" flipY="1"/>
	   
  <!-- Differential drive controller  -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <rosDebugLevel>Debug</rosDebugLevel>
      <publishWheelTF>false</publishWheelTF>
      <robotNamespace>/</robotNamespace>
      <publishTf>1</publishTf>
      <publishWheelJointState>false</publishWheelJointState>
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <leftJoint>front_left_wheel_joint</leftJoint>
      <rightJoint>front_right_wheel_joint</rightJoint>
      <wheelSeparation>0.150</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <broadcastTF>1</broadcastTF>
      <wheelTorque>40</wheelTorque>
      <wheelAcceleration>1.8</wheelAcceleration>
      <commandTopic>cmd_vel</commandTopic>
      <odometryFrame>odom</odometryFrame> 
      <odometryTopic>odom</odometryTopic> 
      <robotBaseFrame>base_footprint</robotBaseFrame>
    </plugin>
  </gazebo> 
</robot>
